import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Template from '../components/template'
import { useEffect, useState } from 'react'
import Questions from '../components/questions'

type Option = {
  text: string,
  id: number
}

type Question = {
  id: number,
  title: string,
  options: Option[]
}


const Home: NextPage = ({data} : any) => {


  const [questions, setQuestions] = useState([]);

  useEffect(() => {
    setQuestions(data.sort(() => Math.random() - Math.random()).slice(0, 10))
  },[])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Template title="Exámen ISTBQ" >
        <Questions questions={questions} />
      </Template>
    </div>
  )
}

export default Home

export async function getServerSideProps() {

  const res = await fetch(`http://localhost:3000/api/questions`)
  const data = await res.json()

  return {
      props:{
        data
      }
  }

}